---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./bootc.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./ext-postgres-operator.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./influxdata.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./longhorn.yaml
  - ./mariadb-operator.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./tyzbit.yaml
  - ./weave-gitops.yaml
