---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-poller-external-secret
  namespace: monitoring
spec:
  target:
    name: unifi-poller-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        UP_UNIFI_DEFAULT_USER: |-
          {{ .unpoller_username }}
        UP_UNIFI_DEFAULT_PASS: |-
          {{ .unpoller_password }}
  data:
    - secretKey: unpoller_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a4d042a-e162-4a28-9537-b03c00f59559
        property: unpoller_username
    - secretKey: unpoller_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a4d042a-e162-4a28-9537-b03c00f59559
        property: unpoller_password
