---
storage:
  encryption_key: ${SECRET_AUTHELIA_STORAGE_KEY}
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
    - name: vpn
      networks:
        - "192.168.0.0/16"
  rules:
    - domain: "echo-server.${SECRET_DOMAIN}"
      policy: bypass
      networks:
        - internal
        - vpn
    - domain: "cyberchef.${SECRET_DOMAIN}"
      policy: bypass
      networks:
        - internal
        - vpn
    - domain: "echo-server.${SECRET_DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]
    - domain: "qbittorrent.${SECRET_DOMAIN}"
      policy: one_factor
    - domain: "radarr.${SECRET_DOMAIN}"
      policy: one_factor
    - domain: "sonarr.${SECRET_DOMAIN}"
      policy: one_factor

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: indirect
  user_verification: preferred
  timeout: 60s
