---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rss-forwarder-external-secret
  namespace: system
spec:
  target:
    name: rss-forwarder-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.toml: |-
          [feeds.github-template]
          url = "https://github.com/onedr0p/flux-cluster-template/commits/main/.atom"
          interval = "10m"
          retry_limit = 5
          sink.type = "discord"
          sink.url = {{ .discord_webhook_url }}
  data:
    - secretKey: discord_webhook_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c8fa7d98-d213-45ae-8ef5-b04b00e7ea7d
        property: discord_webhook_url
