---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-external-secret
  namespace: default
spec:
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Netbox storage
        s3-config.yaml: |
          STORAGE_CONFIG:
            AWS_S3_ENDPOINT_URL: https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
            AWS_S3_REGION_NAME: WEUR
            AWS_STORAGE_BUCKET_NAME: netbox
            AWS_ACCESS_KEY_ID: {{ .access_key_id }}
            AWS_SECRET_ACCESS_KEY: {{ .secret_access_key }}
        # Netbox Init
        NETBOX_PG_PASS: |-
          {{ .netbox_pg_pass }}
        superuser_password: |-
          {{ .superuser_password }}
        superuser_api_token: |-
          {{ .superuser_api_token }}
        secret_key: |-
          {{ .secret_key }}
        email_password: ""
        napalm_password: ""
        redis_tasks_password: ""
        redis_cache_password: ""
        # Postgres Init
        INIT_POSTGRES_DBNAME: |-
          netbox
        INIT_POSTGRES_HOST: |-
          postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: |-
          {{ .netbox_pg_user }}
        INIT_POSTGRES_PASS: |-
          {{ .netbox_pg_pass }}
        INIT_POSTGRES_SUPER_USER: |-
          {{ .pg_super_user }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .pg_super_pass }}
  data:
    - secretKey: pg_super_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: username
    - secretKey: pg_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: password
    - secretKey: netbox_pg_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: netbox_pg_user
    - secretKey: netbox_pg_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b0f64f2d-7a43-4ac2-9b6d-b02e01525324
        property: netbox_pg_pass
    - secretKey: access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 32aff4b6-d46b-4d69-a692-b03d00fcec3b
        property: access_key_id
    - secretKey: secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 32aff4b6-d46b-4d69-a692-b03d00fcec3b
        property: secret_access_key
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 32aff4b6-d46b-4d69-a692-b03d00fcec3b
        property: secret_key


