---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netbox
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      chart: netbox
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bootc
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/tgenannt/netbox
      pullPolicy: IfNotPresent
      tag: "v3.6.1"
    superuser:
      name: admin
      email: admin@${SECRET_DOMAIN}
    admins:
      - ["admin", "admin@${SECRET_DOMAIN}"]
    logging:
      disable_existing_loggers: false
      handlers:
        console:
          class: logging.StreamHandler
      loggers:
        netbox.authentication.*:
          handlers:
            - console
          level: DEBUG
      version: 1
    remoteAuth:
      enabled: false
    loginRequired: false
    storageBackend: storages.backends.s3boto3.S3Boto3Storage
    existingSecret: netbox-secret
    metricsEnabled: true
    postgresql:
      enabled: false
    redis:
      enabled: false
    tasksRedis:
      host: redis.database.svc.cluster.local
    cachingRedis:
      host: redis.database.svc.cluster.local
    externalDatabase:
      host: postgres-rw.database.svc.cluster.local
      port: 5432
      database: netbox
      username: netbox
      existingSecretName: "netbox-secret"
      existingSecretKey: "NETBOX_PG_PASS"
    persistence:
      enabled: false
    reportsPersistence:
      enabled: false
    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: ip-network-outline
      hosts:
        - host: &host "netbox.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: netbox
                  port:
                    number: 80
      tls:
        - hosts:
            - *host
    init:
      image:
        repository: docker.io/library/busybox
        tag: 1.36.1
        pullPolicy: IfNotPresent
    extraInitContainers:
      - image: ghcr.io/onedr0p/postgres-init:16.6
        imagePullPolicy: IfNotPresent
        name: init-db
        securityContext:
          runAsUser: 999
        envFrom: &envFrom
          - secretRef:
              name: netbox-secret
    extraConfig:
      - secret:
          secretName: netbox-secret
    updateStrategy:
      type: RollingUpdate
    worker:
      enabled: true
      nodeSelector:
        kubernetes.io/arch: amd64
      updateStrategy:
        type: RollingUpdate
