apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-extra
    namespace: flux-system
stringData:
    SECRET_INFRA_DOMAIN: ENC[AES256_GCM,data:Ogu66H4RKtYv0w==,iv:98Ju5iRTiQa0EqLKF84D+r3MHOQwQP8Q/F61VjJWwlE=,tag:nAy2lS3DTIdanDNRKHYrnw==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:QRqCshiUkpUg1pcM7wzAMd309nwpDcO3y1+3D4HaRWo=,iv:vj4r8ObGT/gaKQsIBeC3o/MAHSeefRCRBx/FJx5llL4=,tag:dvQRR1LsVH26kI7elEfpIw==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:4hCTie6A58+ZSw==,iv:Y0KKTu7SFhXvctn0Det4DgnRlCfe3kRJW/Chskbu1Qk=,tag:N9KXCxqqSkAw9KNJc1s4+g==,type:str]
    SECRET_NAS_IP_STREAMING: ENC[AES256_GCM,data:X1UKX4tPjbuCdg==,iv:ijot8OSKW91JOQPWILKzUrFeOByNiHllZVreLOUvtE0=,tag:D1vujqd+eS/G3S4/nSsqtQ==,type:str]
    SECRET_MALTRAIL_IP: ENC[AES256_GCM,data:JtV0CD/W1YdW,iv:3dMvxzM0ThkSc2uoTYtxhaqtDvHsQzlBxLV9P6ix2K0=,tag:mjQmtFKVWJ6bOCslZKcrXQ==,type:str]
    SECRET_MAIN_PC_IP: ENC[AES256_GCM,data:AUg1qpqubB8=,iv:EqAAe7VQCV6n1C8bFqaGumSN6xSbTWgaMVZTJq+rS2o=,tag:35QUEEpIRnkogq5rdPJp+Q==,type:str]
    SECRET_INFLUX_DB_TOKEN: ENC[AES256_GCM,data:N//NYVSIO/eTawzhv7YrYfxfgdz1Q+AR0VcvTsZuJb4=,iv:pu2/JyXIDdVEuULwkJt8d0PjUm2DBTIvbyhTxBfQYoA=,tag:m4L0bOGt8p4VlscB/3uphw==,type:str]
    SECRET_UNIFI_CONTROLLER_URL: ENC[AES256_GCM,data:kKAQB3tISWO628erajBnwdRcgnHXrTU=,iv:/D2QMBT0VaioBf6RJDPkErCDmxMIu+ZJjfObC7/a0lk=,tag:X5gz6QS/VDv96mmTn5ZYPw==,type:str]
    SECRET_AUTHELIA_BASE_DN: ENC[AES256_GCM,data:CHNAALeB+yAYZoVY4A4Q,iv:CJrrLXgF+vIa+nrQObbb3c1RxeDvooaBVF5Y3QfOhZo=,tag:wdWjILRx6isADRtE498CcQ==,type:str]
    SECRET_AUTHELIA_STORAGE_KEY: ENC[AES256_GCM,data:ZzA2dreLkNw66AW9TnSzFn7XEOW5hGyu5JxTGDd/nsCdceFm,iv:zbylJ/x1DEb85zq2De59nn5SxOCVr6zxiakg8AVdRMg=,tag:0lWZm2RzwGgqIM5E13aEbA==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:jGvb8NM=,iv:eJoLQx5toWxz47mA0GgsePvmGYwE1Iu5N3Rr8h1eZKU=,tag:XnHafwoe8yGeW7EUPDAHCA==,type:str]
    SECRET_VPN_SHADOWSOCKS_PASSWORD: ENC[AES256_GCM,data:4O7/oKtUADeDkPAwt30=,iv:a/VCbCW6zUAJOLWJL3riuZf+hwSy5V4ibJJgbbd9eLE=,tag:XP06BSuKTMRxeC1gzGy2Ag==,type:str]
    SECRET_SPEEDTEST_SERVER_ID: ENC[AES256_GCM,data:MUoALw==,iv:zZHSJuyzB18kz6uRcnbYKz8+laZfkqIC7ltBPo0R0o0=,tag:0Q82BMEkbvCIwXVxRwam7A==,type:str]
    SECRET_GMAIL_ADDRESS: ENC[AES256_GCM,data:0JRIGKVbK4+fcFsQXqxT/g==,iv:FNyI4TSfQksPENAgbb+87V3tXwoh0b3BpWv/FAmceJE=,tag:oz2ATEcucGbnUFeeY8Pn6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x05r8tdwj7ruzqffcuamt3v7gnf82ldcmrjq8zd3fnh9593grd8sktr4ws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UFNpR3JMd2d6TC9ndjRI
            SU5GZzhHeEUwYnhzRWhrejBSUlg5NXF0YldvCjlLQnk2MnZmcmgzcnQ3bkxDM2Qv
            dm1LUW9oZXFXWjJPMzl6bkRJaGJXbFUKLS0tIEVHbzYxUnY1SUE1eFVsRjdkaVMz
            dVU0WEEza0VOT3F3T2lLZVJZeVl3RWcKRwnKcxnKxs7/o843qFW4hqEByUqO4R+O
            RK+P9f00q+S0Ur50GkCvHj0tKQF3RKtZWB+v74iRfn1SI5f8RdCZAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T13:37:33Z"
    mac: ENC[AES256_GCM,data:QBPvc3TmPDA1NksvG5gSJG91kjIrYnHB93c0g6hjPplglmu4QLCnYFSP4m+tOPiovyGHHVjSmAP0h+LW28O4Y7xqh0Fly2NwILE8LRXhAaawuu0a9iIicOoBrvB1O56Ajkt2RbUxSArphcxplWSOtc0EWkaF6ZzEzPWqjnMSp6Q=,iv:LK5sroQz7R4j+AN65GnHCX/iCuQBwD+rQNeGEOpWI7w=,tag:lUVEUU2mejlCQj9giHeseQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
