---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "10.10.1.20"
  CLUSTER_CIDR: "10.42.0.0/16"
  CILIUM_BGP_PEER: "10.20.1.1"
  CILIUM_BGP_CIDR: "10.20.1.0/24"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.10.0.0/23"
