---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./authelia/ks.yaml
  - ./gmail-operator/ks.yaml
  - ./intel-device-plugins/ks.yaml
  - ./kyverno/ks.yaml
  - ./lldap/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./ntfy/ks.yaml
  - ./rss-forwarder/ks.yaml
  - ./theme-park/ks.yaml
