---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: database
spec:
  interval: 60m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 60m
  values:
    fullnameOverride: *app
    image:
      repository: influxdb
      tag: 2.7.1
    pdb:
      create: false
    env:
      - name: TZ
        value: "${TIMEZONE}"
    adminUser:
      organization: "lab"
      user: "admin"
      retention_policy: "30d"
      bucket: "default"
      token: "${SECRET_INFLUX_DB_TOKEN}"
    persistence:
      enabled: true
      useExisting: true
      name: influxdb-pvc
    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/appName: Influxdb
        hajimari.io/icon: simple-icons:influxdb
      pathType: Prefix
      hostname: "influxdb.${SECRET_DOMAIN}"
      hosts:
        - &host "influxdb.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
  valuesFrom:
    - targetPath: adminUser.user
      kind: Secret
      name: influxdb-secret
      valuesKey: admin-username
    - targetPath: adminUser.password
      kind: Secret
      name: influxdb-secret
      valuesKey: admin-password
