---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./external-secret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ./external/nas.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - ./config/config.yaml
  - name: gatus-dashboard
    files:
      - gatus-dashboard.json=https://raw.githubusercontent.com/aumer-amr/labv2/main/raw/gatus-grafana.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
