---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-gatus
  namespace: system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: LDAP
        group: system
        url: https://lldap.${SECRET_DOMAIN}
        interval: 1m
        conditions: ["[STATUS] == 200"]
        alerts: [{ type: discord }]
        ui:
          hide-hostname: true
          hide-url: true
